server:
  port: ${port:0}
spring:
  application:
    name: session-logs
  rabbitmq:
    host: localhost
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.uri:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true